### ISSUE TITLE
running spectralDNS2D.py

### ISSUE THREAD

**Issue by francispoulin** [mikaem/spectralDNS#4]
I see that since last time I downloaded this you added the MPI into the 2D problem.  That is a great help.

I wanted to try running the code but I seem to have some difficulties importing pylab.  I can import it if I don't import MPI_knee but as it stands there seems to be a clash between the two.

I ran it on my ubuntu machine and it seemed to run fine.  But when I run it on my mac (with anaconda) I have problems.  

Sorry for the bother but any advice would be greatly appreciated.

Best regards,
Francis

>>> from MPI_knee import mpi_import, MPI
>>> from numpy import *
>>> from pylab import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "MPI_knee.py", line 249, in import_module_level
    head, name, buf = load_next(parent, None if level < 0 else parent, name, buf)
  File "MPI_knee.py", line 153, in load_next
    result = import_submodule(mod, subname, buf)
  File "MPI_knee.py", line 204, in import_submodule
    m = imp.load_module(fullname, fp, filename, stuff)
  File "/Applications/anaconda/lib/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "MPI_knee.py", line 249, in import_module_level
    head, name, buf = load_next(parent, None if level < 0 else parent, name, buf)
  File "MPI_knee.py", line 153, in load_next
    result = import_submodule(mod, subname, buf)
  File "MPI_knee.py", line 204, in import_submodule
    m = imp.load_module(fullname, fp, filename, stuff)
  File "/Applications/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py", line 180, in <module>
    from matplotlib.cbook import is_string_like
  File "MPI_knee.py", line 253, in import_module_level
    tail, name, buf = load_next(tail, tail, name, buf)
  File "MPI_knee.py", line 153, in load_next
    result = import_submodule(mod, subname, buf)
  File "MPI_knee.py", line 204, in import_submodule
    m = imp.load_module(fullname, fp, filename, stuff)
  File "/Applications/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 13, in <module>
    from six.moves import xrange, zip
  File "MPI_knee.py", line 253, in import_module_level
    tail, name, buf = load_next(tail, tail, name, buf)
  File "MPI_knee.py", line 160, in load_next
    raise ImportError("No module named %.200s" % name)
ImportError: No module named moves
>>> from mpi4py import MPI
>>> import time
>>> from src.mpi.wrappyfftw import *
>>> from src.utilities.commandline import *

**Comment by mikaem** [comment]
Hi Francis,

It seems like there is an issue with MPI_Knee and pylab. However, MPI_Knee is only necessary if you are planning on running on hundreds, maybe thousands of processors, so in case you are not the MPI_Knee and with mpi_import can be safely removed.

Best regards

Mikael


On 31 Mar 2015, at 16:10, francispoulin <notifications@github.com<mailto:notifications@github.com>> wrote:

ImportError: No module named moves

**Comment by francispoulin** [comment]
Helle Mikael,

Thank you. I removed three lines and it runs both in serial and in parallel.  At some point I would like to run this on hundreds of cores but for the moment I am thinking 8 or so.  Maybe after I learn more how it works I can figure out how MPI_Knee works.  For the moment I'll play with now things scale on my desktop.

Thanks again.

Francis

**Comment by francispoulin** [comment]
Hello again,

I have tried running spectralDNS2D.py on my ubuntu machine, where I didn't have to do anything.  All I've done is changed M in the TaylorGreen.py to make it a finer resolution.  Mostly to see how things scale.  I made it as large as 12.  

With np = 1it runs 16m34s.  

With np = 2 it runs in 20m13s.

It seems to be running more slowly.

I am sorry if I misunderstood but should the TaylorGreen problem run with the parallel mpi?
If there is another problem you suggest I run please let me know and I will give it a try.  At the moment I am just trying to get some results as to how it scales on my computers.

Thanks again,
Francis

**Comment by francispoulin** [comment]
Little update.

I just tried np = 4 and get it down to 10m37sec, which is very efficient in comparison to the np=2 case.  Maybe there is some overhead with setting up MPI that causes the slowdown from 1 to 2 but pays off from 2 to 4?  I will try np = 8 to see how that does.

**Comment by mikaem** [comment]
Hi Francis,

Note that there is usually a penalty in moving from 1 to 2 processors since the first requires no communications at all and as such may use more efficient routines (see e.g., first lines of rfft2_mpi). Other than that I should warn you that good scaling requires good interconnect networks and on a laptop these may not be optimal. Using a dedicated parallel supercomputer (BlueGene/P) with very good communication I have now run the 3D code using 2048 processors and obtain more or less exactly the same scaling as a pure C++ code that is using the mpi routines directly from FFTW.

Best regards

Mikael


On 01 Apr 2015, at 20:12, francispoulin <notifications@github.com<mailto:notifications@github.com>> wrote:


Little update.

I just tried np = 4 and get it down to 10m37sec, which is very efficient in comparison to the np=2 case. Maybe there is some overhead with setting up MPI that causes the slowdown from 1 to 2 but pays off from 2 to 4? I will try np = 8 to see how that does.

**Comment by francispoulin** [comment]
Hello Mikael,

Thanks for your response.

I am running this on my desktop that has 2 8 core processors.  So the connectivity is good up to 8.  

I am sure that things parallelize much better in 3D for a particular resolution because each core has more to do, and the overhead is well worth it.  I would have thought that 4096x4096 would parallelize pretty well.  When I did 8 cores I had around the same as 4.

I have had a student do some tests of a pseudo-spectral FFTW based code in fortran and on 1024x1024 it scales well up to 16 cores, maybe more.  I am hoping to convince myself that I can get good scalability in 2D in python using mpi4py and pyfftw.  Your code seems to be doing just that.  

Maybe my preliminary tests weren't set up correctly. I will try them again tomorrow and see how things scale.

Thanks again for your time and sharing this very impressive code of yours.

Francis

**Comment by ketch** [comment]
I suggest that we follow generally-agreed best practices and NOT import pylab, but instead import the individual packages we need.  See http://nbviewer.ipython.org/github/Carreau/posts/blob/master/10-No-PyLab-Thanks.ipynb for justification.

**Comment by mikaem** [comment]
Ah, I didn't know. I'll replace any pylab imports from the demos
